version: "3.8"
services:
  database:
    image: postgres:14
    volumes:
      - db_pg_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      # Sets the superuser password for PostgreSQL
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextchapter_development
volumes:
  db_pg_data:
